// <auto-generated />
using MediatorCrud.Pdtcxt;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediatorCrud.Migrations
{
    [DbContext(typeof(Pdtdata))]
    [Migration("20250716125225_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MediatorCrud.Models.Pdt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PdtDescr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdtName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PdtPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PdtStk")
                        .HasColumnType("int");

                    b.Property<int>("catgryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("catgryId");

                    b.ToTable("Pdts");
                });

            modelBuilder.Entity("MediatorCrud.Models.ctgry", b =>
                {
                    b.Property<int>("catgryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("catgryId"));

                    b.Property<string>("catgryNmae")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("catgryId");

                    b.ToTable("Ctgries");

                    b.HasData(
                        new
                        {
                            catgryId = 1,
                            catgryNmae = "Mobile"
                        },
                        new
                        {
                            catgryId = 2,
                            catgryNmae = "Laptop"
                        },
                        new
                        {
                            catgryId = 3,
                            catgryNmae = "TV"
                        },
                        new
                        {
                            catgryId = 4,
                            catgryNmae = "Audio"
                        });
                });

            modelBuilder.Entity("MediatorCrud.Models.Pdt", b =>
                {
                    b.HasOne("MediatorCrud.Models.ctgry", "catgry")
                        .WithMany("Pdts")
                        .HasForeignKey("catgryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("catgry");
                });

            modelBuilder.Entity("MediatorCrud.Models.ctgry", b =>
                {
                    b.Navigation("Pdts");
                });
#pragma warning restore 612, 618
        }
    }
}
